name: example
version: 0.0.1
description: >
  Just an example, not for publishing.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/enum_class.dart

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  enum_class: '^0.0.1''

dev_dependencies:
  enum_class_generator: '^0.0.1'
