name: example
version: 1.1.0
description: >
  Just an example, not for publishing.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/enum_class.dart

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  enum_class: '^1.1.0'

dev_dependencies:
  enum_class_generator: '^1.1.0'
