name: enum_class
version: 0.0.1
description: >
  Dart classes as enums. This library is the runtime dependency.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/enum_class.dart

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  built_collection: '^1.0.0'

dev_dependencies:
  test: any
