name: enum_class_generator
version: 0.0.4
description: >
  Dart classes as enums. This library is the dev dependency.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/enum_class.dart

environment:
  sdk: '>=1.12.0-dev.5.2 <2.0.0'

dependencies:
  analyzer: '>=0.26.1 <1.0.0'
  built_collection: '^1.0.0'
  enum_class: '^0.0.4'
  source_gen: '>=0.4.3 <1.0.0'
  quiver: '>=0.21.0 <0.22.0'

dev_dependencies:
  test: any
